### ISSUE TITLE
Usage of encode/decode

### ISSUE THREAD

**Issue by janwirth** [turboMaCk/any-dict#10]
I'm a bit lost and there is no documentation. Why can I not simply pass encoders for both keys and values?

**Comment by turboMaCk** [comment]
decoder and encoders are meant for decoding JSON object. Object keys in JSON are always string, thus having `String -> k` function is all that is necessary. For any other case one can still define own decoding / encoding logic but this is not easy to provide in library because of interactions between comparable and key type. providing decoder for JSON object is safe though because there is known unique string variant for key type.

**Comment by janwirth** [comment]
If you have the time, can you please provide an example of how this would be used to encode and decode
```elm
type alias MyType = Dict.Any.Any {name : String, age: Int} Int
```

Because it's still not clear to me.

**Comment by turboMaCk** [comment]
no worries. I'm glad you've raised the issue. Seems this should be worth clarifying. I'll try to extend the documentation with example for this.

**Comment by janwirth** [comment]
I personally have resorted to encoding them as a list of tuples. I do not understand why the signature can not be:
```elm
Dict.Any.encode : (a -> Value) -> (b -> Value) -> Dict.Any.Any comparable a b -> Encode.value

Dict.Any.decode : (a -> comparable ) -> Decode.Decoder a -> Decode.Decoder b -> Decode.Decoder (Dict.Any.Any comparable a b)
```

**Comment by turboMaCk** [comment]
> I personally have resorted to encoding them as a list of tuples

This library provides all the primitives you need to write any type of custom decoder for your AnyDict types. Even provided decode and encode use just functions from public api. If you would like some other implementation you're free to just write it.
