### ISSUE TITLE
Consider integrating with the Comparison explicit typeclass

### ISSUE THREAD

**Issue by nikita-volkov** [turboMaCk/any-dict#6]
I've released a package providing explicit typeclasses. It contains Comparison, which is what you need in this package. See https://package.elm-lang.org/packages/nikita-volkov/typeclasses/latest

**Comment by turboMaCk** [comment]
Thanks @nikita-volkov I was actually thinking about creating similar package myself many times. But it will be definitely challenging to force adoption of something like this.

Also this is not really usable for purpose of this package. Because of `Dict` from stdlib we're forced to use translation to `comparable` here which we can't constreuct from `(a -> a -> Order)`. So I think for time being this can't be addpoted for purposes of this library.

**Comment by nikita-volkov** [comment]
Oh yeah. I see that now. Haven't used this library before :) Sorry for bothering

**Comment by turboMaCk** [comment]
np I'm glad I learned about your lib at least. All this being said I would love to see a change in official Dict which would make it possible to use with `Order` type.
